export const mainColor = "#FF4791";
//export const secondColor = "#52B6FF"
export const textColor = "#FFFFFF";
export const textFormColor = "#7E7E7E";
export const backgroundColor = "#0E0E13";
// export const planWhiteColor = "#FFFFFF";
// export const planGoldColor = "#FFF16F";
// export const planGreenColor = "#56D49F";
export const cancelColor = "#FF4747";
